### ISSUE TITLE
应添加本 python 包的安装、测试说明

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#15]
应在 README.md 中，注明本模块的安装、测试方法。

我用 python3 环境，不但安装不了，测试也报错。

```
======================================================================
ERROR: test_pcap_file_header_2 (__main__.TestAnalysisPcap)
测试pcap_file_header创建的字典value
----------------------------------------------------------------------
Traceback (most recent call last):
  File "AnalysisPcapTest.py", line 66, in test_pcap_file_header_2
    obj5 = self.creat_new_analysispcap().pcap_file_header()
  File "AnalysisPcapTest.py", line 15, in creat_new_analysispcap
    self.obj1 = AnalysisPcap(pcapath, path2)
  File "/xxx/python3.6/site-packages/analysispcap-0.1-py3.6.egg/analysispcap/analysisPcap.py", line 15, in __init__
    self.fpcap = open(self.pcapath, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/wireshark.pcap'

----------------------------------------------------------------------
Ran 13 tests in 0.002s

FAILED (errors=12)
```

**Comment by sunpudding** [comment]
已在README.md中进行说明，可进行查看
